import React, { useEffect } from "react";
import "./ViewTestiBody.scss";
import { Link } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { deleteTestimonial, fetchTestimonials } from "../../store/testimonialSlice";

// const testimonials = [
//   {
//     img: "/path/TestimonialImg01.jpg",
//     clientImg: "/path/ClientImg01.jpg",
//     name: "MaKayla P.",
//     company: "Disney",
//     content:
//       "As a content creator, I was always on the lookout for a tool that could help me keep up with the demand. The AI-driven content tool has been a game-changer. It generates high-quality content in a fraction of the time it used to take me.",
//     categories: [1, 3, 5],
//   },
//   {
//     img: "/path/TestimonialImg02.jpg",
//     clientImg: "/path/ClientImg02.jpg",
//     name: "Andrew K.",
//     company: "Samsung",
//     content:
//       "I've tried several content generation tools, but this AI-driven tool is by far the best. It understands my brand's voice and consistently produces content that resonates with my audience!",
//     categories: [1, 2, 4],
//   },
//   {
//     img: "/path/TestimonialImg03.jpg",
//     clientImg: "/path/ClientImg03.jpg",
//     name: "Lucy D.",
//     company: "Rio",
//     content:
//       "Content creation used to be a bottleneck in our workflow, but not anymore. This AI tool is intuitive and produces top-notch content every time. It's like having an extra team member who never sleeps! Definitely recommend.",
//     categories: [1, 2, 5],
//   },
//   {
//     img: "/path/TestimonialImg04.jpg",
//     clientImg: "/path/ClientImg04.jpg",
//     name: "Pavel M.",
//     company: "Canon",
//     content:
//       "The quality of the content generated by this AI tool is outstanding. It has taken our content marketing to new heights, allowing us to publish more frequently without compromising on quality. Highly recommended for anyone.",
//     categories: [1, 4],
//   },
//   {
//     img: "/path/TestimonialImg05.jpg",
//     clientImg: "/path/ClientImg05.jpg",
//     name: "Miriam E.",
//     company: "Cadbury",
//     content:
//       "The AI-driven content tool has been a lifesaver for my marketing agency. We can now produce high-quality content for multiple clients quickly and efficiently. It's an invaluable asset to our team.",
//     categories: [1, 3, 5],
//   },
// ];

const ViewTestiBody = () => {

  const dispatch = useDispatch();

  const { data: testimonials, loading } = useSelector((state) => state.testimonials);

  useEffect(() => {
    dispatch(fetchTestimonials());
  }, [dispatch]);

  const handleDelete = (testimonialId) => {
    dispatch(deleteTestimonial(testimonialId));
  }

  return (
    <div className="testimonials-table-container">
      
      {loading ? 
        (
          <div class="loader">
            <div class="loader_cube loader_cube--color"></div>
            <div class="loader_cube loader_cube--glowing"></div>
          </div>
        )
        :
        (
          <>
            <div className="header">
              <h2>Testimonials</h2>
              <Link to='/addtesti'>
                <button className="add-testimonial-btn">Add New Testimonial</button>
              </Link>
            </div>
            <table className="testimonials-table">
              <thead>
                <tr>
                  <th>Testimonial Image</th>
                  <th>Client Image</th>
                  <th>Name</th>
                  <th>Company</th>
                  <th>Content</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {testimonials.map((testimonial, index) => (
                  <tr key={index}>
                    <td>
                      <img src={testimonial.img} alt="testimonial" className="testimonial-icon" />
                    </td>
                    <td>
                      <img src={testimonial.clientImg} alt="client" className="client-icon" />
                    </td>
                    <td>{testimonial.name}</td>
                    <td>{testimonial.company}</td>
                    <td>{testimonial.content}</td>
                    <td>
                      <button 
                        onClick={() => handleDelete(testimonial._id)}
                        className="delete-btn"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
    </div>
  );
};

export default ViewTestiBody;
